URL:
  HOME_REQUEST_URL: https://www.zhihu.com/
  INDEX_REQUEST_URL: https://www.zhihu.com/signup
  LOGIN_REQUEST_URL: https://www.zhihu.com/api/v3/oauth/sign_in
  BATCH_REQUEST_URL: https://zhihu-web-analytics.zhihu.com/api/v1/logs/batch
  CAPTCHA_REQUEST_URL: https://www.zhihu.com/api/v3/oauth/captcha?lang=en
  TOPSTORY_REQUEST_URL: https://www.zhihu.com/api/v3/feed/topstory
  FIND_REQUEST_URL: https://www.zhihu.com/node/ExploreAnswerListV2
  TOPIC_REQUEST_URL: https://www.zhihu.com/node/TopicFeedList
  SHARETEXT_REQUEST_URL: https://www.zhihu.com/answer/134481898/sharetext
  URL_FOLLOWING_QUESTION_COUNT: https://www.zhihu.com/api/v4/me?include=following_question_count
  URL_SWITCHS: https://www.zhihu.com/api/v4/me/switches?include=is_answer_rewardable%2Ccould_set_poster%2Cis_answer_oppose_reason_visiable
  URL_SUPPORTED_COUNTRISE: https://www.zhihu.com/api/v3/oauth/sms/supported_countries

AUTH:
  # 这是固定的
  AUTHORIZATION: c3cef7c66a1843f8b3a9e6a1e3160e20

HEADERS:
  Accept: application/json, text/plain, */*
  Accept-Language: zh-CN,zh;q=0.9
  X-Requested-With: XMLHttpRequest
  Host: www.zhihu.com
  Origin: https://www.zhihu.com
  Referer: https://www.zhihu.com/
  User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36

POST_DATAS:
  client_id: c3cef7c66a1843f8b3a9e6a1e3160e20
  grant_type: password
  source: com.zhihu.web
  lang: en
  ref_source: homepage
  utm_source: ''